### PR TITLE
feat: 158 stats

### LINKED ISSUE #158: stats
### Description

Add a component stats, to measure the performance of the scene

### Suggested solution

See https://github.com/pmndrs/drei#stats

### Alternative

statsGI

### Additional context

When finish this component add a new issue to add statsGI

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by JaimeTorrealba**
closes #158

### CODE REVIEW

**Comment by alvarosabu** [comment]
Hi @JaimeTorrealba interesting one 😊, can you please check the linters?

**Review by alvarosabu — CHANGES_REQUESTED** [review]
Hi @JaimeTorrealba interesting one 😊, can you please check the linters?

**Comment by alvarosabu** [comment]
9:58:39 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
9:58:16 PM: build-image version: 20e1f1f500e4cbad9ea8a99bd40807bef3093551 (focal)
9:58:16 PM: buildbot version: d7125d73ee51e5ae94a98ff24da5d2bcd8321340
9:58:16 PM: Fetching cached dependencies
9:58:16 PM: Starting to download cache of 391.4MB
9:58:20 PM: Finished downloading cache in 3.716s
9:58:20 PM: Starting to extract cache
9:58:24 PM: Finished extracting cache in 3.489s
9:58:24 PM: Finished fetching cache in 7.273s
9:58:24 PM: Starting to prepare the repo for build
9:58:24 PM: Preparing Git Reference pull/166/head
9:58:25 PM: Custom build command detected. Proceeding with the specified command: 'pnpm run build && pnpm docs:build'
9:58:26 PM: Starting to install dependencies
9:58:26 PM: Python version set to 3.8
9:58:26 PM: Attempting Ruby version 2.7.2, read from environment
9:58:26 PM: Using Ruby version 2.7.2
9:58:27 PM: Started restoring cached go cache
9:58:27 PM: Finished restoring cached go cache
9:58:28 PM: Installing Go version 1.19.12 (requested 1.19.x)
9:58:33 PM: go version go1.19.12 linux/amd64
9:58:34 PM: Using PHP version 8.0
9:58:34 PM: Started restoring cached Node.js version
9:58:36 PM: Finished restoring cached Node.js version
9:58:37 PM: v18.17.1 is already installed.
9:58:37 PM: Now using node v18.17.1 (npm v9.6.7)
9:58:37 PM: Enabling Node.js Corepack
9:58:37 PM: Started restoring cached build plugins
9:58:37 PM: Finished restoring cached build plugins
9:58:37 PM: Started restoring cached corepack dependencies
9:58:37 PM: Finished restoring cached corepack dependencies
9:58:38 PM: Found pnpm version (8.4.0) that doesn't match expected ()
Usage Error: Invalid package manager specification in CLI arguments; expected a semver version, range, or tag
9:58:38 PM: $ corepack prepare [--activate] [--all] [--json] [-o,--output] ...
9:58:38 PM: pnpm workspaces detected
9:58:38 PM: Started restoring workspace docs node modules
9:58:38 PM: Finished restoring workspace docs node modules
9:58:38 PM: Started restoring workspace playground node modules
9:58:38 PM: Finished restoring workspace playground node modules
9:58:38 PM: Started restoring workspace root node modules
9:58:38 PM: Finished restoring workspace root node modules
9:58:38 PM: Installing npm packages using pnpm version 8.4.0
9:58:39 PM: Scope: all 3 workspace projects
9:58:39 PM:  WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
9:58:39 PM: Lockfile is up to date, resolution step is skipped
9:58:39 PM:  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/gsap/3.12.2' in pnpm-lock.yaml
9:58:39 PM: This issue is probably caused by a badly resolved merge conflict.
9:58:39 PM: To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
9:58:39 PM: Error during pnpm install
9:58:39 PM: Build was terminated: dependency_installation script returned non-zero exit code: 1
9:58:39 PM: Failing build: Failed to install dependencies

**Comment by JaimeTorrealba** [comment]
Is still give me problems, the lock @alvarosabu 
https://github.com/Tresjs/cientos/pull/166/commits/05b9df28e39d1f72552bb526fe269c33120b3095#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb

**Pull request merged**
