### PR TITLE
feat(cientos): Add `CustomShaderMaterial` wrapper

### LINKED ISSUE #109: Custom shader material
### Description

drop_CSM_demo

We can create a wrapper using extend to add CSM and apply shaders to other materials, as we can see in that example. We're applying vertex shader to a physical material using the [glass demo](https://playground.tresjs.org/experiments/glass-material),

### Suggested solution

a wrapper around https://www.npmjs.com/package/three-custom-shader-material

### Alternative

I don't know if there are another alternatives, but CSM is one of the most used

### Additional context

The Idea is to create just a wrapper

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kekkorider**
This PR adds a `<CustomShaderMaterial />` wrapper around the [CustomShaderMaterial](https://www.npmjs.com/package/three-custom-shader-material) package.

At the moment the dedicated playground page displays a black torus knot despite the properties I'm passing to it 🥲

@alvarosabu @JaimeTorrealba I'm here again asking for your support 🥲

Screenshot 2023-10-19 alle 16 27 38

Closes #109

### CODE REVIEW

**Comment by alvarosabu** [comment]
@kekkorider let me check

**Comment by alvarosabu** [comment]
Checking their docs:

> When extending already extended material, variables, uniforms, attributes, varying, and functions are NOT scoped to the material they are defined in. Thus, you WILL get redefinition errors if you do not manually scope these identifiers.

Maybe that's the warning

```
Function copy already exists on CSM, renaming to base_copy
```

**Comment by alvarosabu** [comment]
@kekkorider check now 😉

**Comment by kekkorider** [comment]
@alvarosabu @JaimeTorrealba I guess this is ready for review 🥸

For some reason the latest deploy failed, maybe a manual redeploy can fix this (?)

**Review by alvarosabu — APPROVED** [review]
Nice job man, looks pretty cool

**Pull request merged**
