### PR TITLE
feat: add stats-gl component

### LINKED ISSUE #197: Stats-gl
### Description

Add a component, stats-gl, to measure the performance of the scene

### Suggested solution

See https://github.com/pmndrs/drei#statsgl

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by notarun**
Closes #197 
Still need to add docs I guess 😅

### CODE REVIEW

**Comment by JaimeTorrealba** [comment]
Seems everything fine :)

I'll wait for the docs

**Comment by JaimeTorrealba** [comment]
@alvarosabu Can you help me here? Would be a good idea to move them to peer dependencies?

**Comment by alvarosabu** [comment]
@notarun @JaimeTorrealba what is the difference between stats.js and stats-gl?

**Comment by JaimeTorrealba** [comment]
@alvarosabu stats-gl is a new fancy monitor, with more capabilities than stats.js

https://github.com/RenaudRohlinger/stats-gl

It was adopted by R3F and people like it

**Comment by alvarosabu** [comment]
That being said, make sense to have both @JaimeTorrealba ?

**Comment by JaimeTorrealba** [comment]
I would say yes @alvarosabu, more option to the user is always better

We could think better in the final bundle-size if that's the problem, move to peer-deps (but with clear communication to the users, to avoid the useTweakpane issue)

**Review by JaimeTorrealba — APPROVED** [review]
Excellent work

**Pull request merged**
