### PR TITLE
refactor!: change defineExpose value.value to value.instance

### LINKED ISSUE #160: Investigation, delete value.value to access some components
### Description

Currently some abstraction in cientos, need to be access by value.value at the moment of reference them

As a good DX we need to find a solution to this detail.

The problem is located in the EJ:

defineExpose({
  value: starsRef,
})

### Suggested solution

If you have a good solution, please explain it here

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by andretchen0**
## Context

closes #160

## Progress

| AT | JT | AS | file | former | current or comment |
| -- | -- | -- | -- | -- | -- |
| ✅ | | | src/core/abstractions/AnimatedSprite/component.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/abstractions/Lensflare/component.vue | `value` | `instance` |
|   | | | src/core/abstractions/useFBO/component.vue | `value` | `instance` |
|   | | | src/core/abstractions/useSurfaceSampler/component.vue | nothing to do| |
|   | ✅ | | src/core/abstractions/GlobalAudio.vue | no `defineExpose` | |
| ✅ | | | src/core/abstractions/Levioso.vue | `value` | `instance` |
|   | | | src/core/abstractions/MouseParallax.vue | nothing to do | |
| ✅ | | | src/core/abstractions/Reflector.vue | `reflectorRef` | `instance` |
| ✅ | | | src/core/abstractions/Text3D.vue | `value` | `instance` |
| | | | | | |
|   | | | src/core/abstractions/useAnimations.ts | nothing to do | |
| ✅ | | | src/core/controls/CameraControls.vue | `value` | `instance` |
| ✅ | | | src/core/controls/KeyboardControls.vue | `value` | `instance` |
| ✅ | | | src/core/controls/MapControls.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/controls/OrbitControls.vue | `value` | `instance` |
| ✅ | | | src/core/controls/PointerLockControls.vue | `value` | `instance` |
| ✅ | | | src/core/controls/ScrollControls.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/controls/TransformControls.vue | no `defineExpose` | `instance` |
| | | | | | |
| ✅ | | | src/core/loaders/SVG/component.vue | `value` | `instance` |
| ✅ | | | src/core/loaders/useFBX/component.vue | `value` | `instance` |
| ✅ | | | src/core/loaders/useGLTF/component.vue | `value` | `instance` |
| | | | src/core/loaders/useProgress | nothing to do | | |
| | | | src/core/loaders/useVideoTexture | nothing to do | | |
| | | | | | |
| ✅ | | | src/core/materials/customShaderMaterial/index.vue | `value` | `instance` |
| ✅ | | | src/core/materials/meshGlassMaterial/index.vue | `MeshGlassMaterialClass` exposed | `instance` |
| ✅ | | | src/core/materials/meshReflectionMaterial/index.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/materials/meshWobbleMaterial/index.vue | no `defineExpose` | `instance` |
| | | | | | |
| ✅ | | | src/core/misc/html/HTML.vue | no `defineExpose` | `instance` | 
| ✅ | | | src/core/misc/useTweakPane/index.ts | nothing to do | |
| ✅ | | | src/core/misc/BakeShadows | nothing to do | |
|   | ✅ | | src/core/misc/Stats.ts | exposes `stats` | |
|   | ✅ | | src/core/misc/Stats.ts | exposes `statsGl` | |
| ✅ | | | src/core/misc/useGLTFExporter.ts | nothing to do | |
| | | | | | |
| ✅ | | | src/core/shapes/Box.vue | `value` | `instance` | 
| ✅ | | | src/core/shapes/CatmullRomCurve3.vue | no `defineExpose` | `instance` | 
| ✅ | | | src/core/shapes/Circle.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Cone.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Dodecahedron.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Icosahedron.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Line2.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/shapes/Octahedron.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Plane.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Ring.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/RoundedBox.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Sphere.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Superfomula.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Tetrahedron.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Torus.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/TorusKnot.vue | `value` | `instance` |
| ✅ | | | src/core/shapes/Tube.vue | `value` | `instance` |
| | | | | | |
| ✅ | | | src/core/staging/Sparkles/component.vue | no `defineExpose` | `instance` |
|   | | | src/core/staging/useEnvironment/component.vue | | docs demo doesn't load |
| ✅ | | | src/core/staging/Backdrop.vue | no `defineExpose` | `instance` |
|   | | | src/core/staging/ContactShadows.vue | | playground/docs demo have errors |
| ✅ | | | src/core/staging/Ocean.vue | `root` | `instance` |
| ✅ | | | src/core/staging/Precipitation.vue | no `defineExpose` | `instance` |
| ✅ | | | src/core/staging/Sky.vue | `root` | `instance` |
| ✅ | | | src/core/staging/Smoke.vue | `value` | `instance` |
| ✅ | | | src/core/staging/Stars.vue | `value` | `instance` |
| | | | | | |
|   | | | src/utils/index.ts | `value.value` | left as is |

### CODE REVIEW

**Comment by andretchen0** [comment]
@JaimeTorrealba @alvarosabu 

Above is a list of changes made to Cientos files.

I've marked with a ✅, all those that I created or where the change to `instance` appeared straightforward.

To help you keep track of things, there's a column for each of you in the table, if you'd like to use it.

Feel free to push changes to this branch.

----

As of [1c4c569](https://github.com/Tresjs/cientos/pull/392/commits/1c4c569a69c4f2c4adfacb4e2b85516aa3bcf38d), I have:

* tested all Cientos playground demos
* tested all Cientos docs pages for errors

I have not tested anything outside of the Cientos package, including Labs.

**Comment by JaimeTorrealba** [comment]
I created an issue for the contact shadow https://github.com/Tresjs/cientos/issues/401. 

The case of the enviroment component is weird it doesn't return the texture but if I logged it appears. Anyways we can solve them later. The rest of the components I think doesn't apply for this "migration"

If you agree we can merge now to the v4

**Review by JaimeTorrealba — APPROVED** [review]

**Comment by andretchen0** [comment]
@JaimeTorrealba , sounds good.

@alvarosabu , do you want to have a look before we merge?

**Review by alvarosabu — APPROVED** [review]
Nothing to add, amazing job 💚

**Pull request merged**
