### PR TITLE
feat(app): 421 Update components to use useLoop instead of useRenderLoop

### LINKED ISSUE #421: Adapt abstractions to `useLoop` instead of `useRenderLoop`
### Description

As a developer using `@tresjs/cientos` I would like to benefit from the new composable and loop logic introduced in v4 https://github.com/Tresjs/tres/pull/673 

### Suggested solution

Update the following abstractions

- [x] Stats.ts
- [x] StatsGL
- [x] Ocean
- [x] Smoke
- [ ] useEnvironment
- [ ] BakeShadows
- [x] Html
- [x] KeyboardControls
- [ ] ContactShadows
- [x] Levioso
- [x] ScrollControls
- [x] useAnimations
- [x] Precipitation
- [x] HolographicMaterial
- [x] MeshWobbleMaterial
- [x] OrbitControls
- [x] MouseParallax
- [x] CameraControls
- [ ] MeshReflectionMaterial
- [ ] Sparkles

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by JaimeTorrealba**
close #421

- [x] Stats.ts
- [x] StatsGL
- [x] Ocean (need test, related to #411 )
- [x] Smoke
- [x] useEnvironment
- [x] Html
- [x] KeyboardControls
- [ ] ContactShadows (demo not working @alvarosabu, related to #230)
- [x] Levioso
- [x] ScrollControls
- [x] useAnimations
- [x] Precipitation
- [x] HolographicMaterial   (need test, related to #411)
- [x] MeshWobbleMaterial
- [x] OrbitControls
- [x] MouseParallax
- [x] CameraControls
- [ ] Sparkles (demo not working)

### CODE REVIEW

**Comment by JaimeTorrealba** [comment]
Hi, currently 3 main things are missing for this one

@alvarosabu could you check please the lint problems with ocean (a problem with the demo that uses SKY) and holographic

@andretchen0 for some reason, Sparkles is not updating can you help me with this one

Contact shadows also have problems, but this comes before.

And useEnviroment needs to be checked (I will do this)

Thanks :)

**Comment by alvarosabu** [comment]
Sure @JaimeTorrealba, I already fixed the issue of the linting for Sky and holographic here #424, just checked Ocean and is solved as well, once that is merge you can merge it here to do the update

For contact shadows the issues are different, it will require its own ticket

**Comment by andretchen0** [comment]
Having a look at `Sparkles`.

**Comment by andretchen0** [comment]
Unsure about `Sparkles`. Maybe we take it offline for now so this can move forward.

I checked it after the linter was updated.

I'm guessing an underlying dependency updated, but I can't find the source atm.

**Comment by JaimeTorrealba** [comment]
Consider that the ContactShadows  and the sparkles will be out of the scope of this PR.

Can we merge this one? @alvarosabu @andretchen0

**Comment by alvarosabu** [comment]
> Consider that the ContactShadows and the sparkles will be out of the scope of this PR.
> 
> Can we merge this one? @alvarosabu @andretchen0

If we take out those 2 yes, I will take over the ContactShadows 👌

**Comment by andretchen0** [comment]
As mentioned on Discord, it seems that the problem with `Sparkles` and `ContactShadows` are due to changes in the way `primitive` is handles by the `v4` core.

I'm ok to wait for a fix before merging, or merge now and retest here afterwards.

**Comment by alvarosabu** [comment]
I agree with @andretchen0, please @JaimeTorrealba check the conflict on the package.json and we are ready to merge

**Review by alvarosabu — APPROVED** [review]

**Pull request merged**
