### PR TITLE
feat(app): Add layerMaterial material to cientos

### PR DESCRIPTION
**Pull request by hawk86104**
Porting the functionality of r3f  ： [layerMaterial](https://github.com/pmndrs/lamina)
finish Preview link: https://ice-gl.gitee.io/icegl-three-vue-tres/#/plugins/basic/materials/layerMaterial
image
The current code is nearly complete, but we still lack API documentation and demo examples.Later, we will incrementally add them one by one.

### CODE REVIEW

**Comment by hawk86104** [comment]
we can use like this:
`
 <Sphere>
      <LayerMaterial
        color="#ffffff"
        lighting="physical"
        :transmission="1"
      >
        <Depth
          colorA="#810000"
          colorB="#ffd0d0"
          :alpha="0.5"
          mode="multiply"
          :near="0"
          :far="2"
          :origin="new THREE.Vector3(100, 100, 100)"
        />
      </LayerMaterial>
    </Sphere>
`

**Comment by JaimeTorrealba** [comment]
@hawk86104 Hi hawk I appreciated the work done here, however I'm not sure about adding this to cientos, let me discuss with the others members. 

The reason of my concern is about the repo, it has been achieved "Lamina has been archived as of April 5, 2023." Also, the creator farazzshaikh reach some important warnings. @andretchen0 @alvarosabu. Please read https://github.com/pmndrs/lamina. Maybe ask farazz. Personally don't like the idea to add a third-party dependency that is already deprecated, and we also have to maintain

To avoid work in some feature that could or couldn't be merged. Please open an issue first and we discuss it first. Please check the contribution guide where we explain this in more detail: https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md

**Comment by hawk86104** [comment]
OK, thank you. I understand. It would be great if there were similar libraries that are maintained all the time.

**Comment by hawk86104** [comment]
@JaimeTorrealba @alvarosabu
I utilized Cientos' approach, adding LayerMaterial and Lightformer, and modifying the Environment, enabling us to replicate R3F use cases using Vue3

for example：
https://hawk86104.github.io/#/plugins/skyBox/newEnvironment
```vue
<Environment :blur="1" background :far="10000">
	<Lightformer :intensity="0.75" :rotation-x="Math.PI / 2" :position="[0, 5, -9]" :scale="[10, 10, 1]" />
	<Lightformer :intensity="4" :rotation-y="Math.PI / 2" :position="[-5, 1, -1]" :scale="[20, 0.1, 1]" />
	<Lightformer :rotation-y="Math.PI / 2" :position="[-5, -1, -1]" :scale="[20, 0.5, 1]" />
	<Lightformer :rotation-y="-Math.PI / 2" :position="[10, 1, 0]" :scale="[20, 11, 1]" />
	<Levioso :speed="5" :floatFactor="2" :rotationFactor="2">
		<Lightformer form="ring" color="red" :intensity="1" :scale="10" :position="[-15, 4, -18]" />
	</Levioso>

	<TresGroup :rotation="[0, 0.5, 0]">
		<TresGroup ref="group">
			<Lightformer v-for="( i, x ) in lightFormerPositions " :key="i" form="circle" :intensity="2"
				:rotation="[Math.PI / 2, 0, 0]" :position="[x, 4, i * 4]" :scale="[3, 1, 1]" />
		</TresGroup>
	</TresGroup>

	<TresMesh :scale="[100, 100, 100]">
		<TresSphereGeometry :args="[1, 64, 64]" />
		<LayerMaterial :side="THREE.BackSide">
			<Color color="#444" :alpha="1.0" mode="normal" />
			<Depth colorA="blue" colorB="black" :alpha="0.5" mode="normal" :near="0" :far="300"
				:origin="new THREE.Vector3(100, 100, 100)" />
		</LayerMaterial>
	</TresMesh>
</Environment>
```
Modified code is available at the following link:https://github.com/hawk86104/icegl-three-vue-tres/tree/master/src/plugins/basic/components/forCientos

If it's valuable, I can selectively port and merge code into Cientos as required.

Finally, I also replicated the car in a generalized manner：
image
https://hawk86104.github.io/#/plugins/industry4/showCar

**Comment by franciscohermida** [comment]
Maybe leave it as an experimental feature in case it is too hard to maintain? At least we have some foundation if someone want to build on top later?

**Comment by hawk86104** [comment]
> Maybe leave it as an experimental feature in case it is too hard to maintain? At least we have some foundation if someone want to build on top later?

Yesterday I copied another car this way very quickly
https://hawk86104.github.io/#/plugins/industry4/showLambo

**Comment by JaimeTorrealba** [comment]
Hi, I hate coming with bad news :( . But after discussing it, we decided to not accept this PR as it is.   This is because we try to not accept external libraries, especially if they are not actively maintained

However, if you change this one, removing the lamina and re-do the whole thing with CSM, we would welcome it. Of course, I understand if you don't want to do this, since it is a lot of work.

Other option is to create your own package (non-official) maintaining by you. We will support you and help with the advertisement :D 

@franciscohermida unfortunately due to experiences this complicates the workflow for us (Specially for me).

**Comment by hawk86104** [comment]
> Hi, I hate coming with bad news :( . But after discussing it, we decided to not accept this PR as it is. This is because we try to not accept external libraries, especially if they are not actively maintained
> 
> However, if you change this one, removing the lamina and re-do the whole thing with CSM, we would welcome it. Of course, I understand if you don't want to do this, since it is a lot of work.
> 
> Other option is to create your own package (non-official) maintaining by you. We will support you and help with the advertisement :D
> 
> @franciscohermida unfortunately due to experiences this complicates the workflow for us (Specially for me).

Haha😄, I totally understand the requirements for official libraries. 
1. So, I'll resubmit a PR with expanded optimizations: Environment, allowing it to mount sub-components, and Lightformer via FBO. 
2. Later on, I'll create my own package and incorporate some functionalities dependent on external libraries.

Once again, I want to express my gratitude to Tres.js and Cientos. I'm also very eager to share them with my friends, especially in China.

**Comment by hawk86104** [comment]
> Hi, @hawk86104 thank you for your understanding and your kind words. I was about to suggest exactly what you propose, to create a PR for Environment and Lightformers 💚
> 
> We are truly grateful for the Chinese community and all the awesome things you are building with Tres

 You're welcome. In fact, I've gained a lot from tres.js as well, and I also want to give back to the tres..js community through contributions.
this is my new PR: https://github.com/Tresjs/cientos/pull/382

**Comment by hawk86104** [comment]
> Hi, I hate coming with bad news :( . But after discussing it, we decided to not accept this PR as it is. This is because we try to not accept external libraries, especially if they are not actively maintained
> 
> However, if you change this one, removing the lamina and re-do the whole thing with CSM, we would welcome it. Of course, I understand if you don't want to do this, since it is a lot of work.
> 
> Other option is to create your own package (non-official) maintaining by you. We will support you and help with the advertisement :D
> 
> @franciscohermida unfortunately due to experiences this complicates the workflow for us (Specially for me).

Sure! Here’s the translation:

Hello, sorry to disturb you.

This is an open-source framework I developed based on tres.js, cientos.js, and other open-source ecosystems. It allows users to quickly implement 3D visualization projects in production through this framework, all within the tres open-source ecosystem. 

We also provide some translated Chinese documentation, a Q&A community, video tutorials, etc. The documentation and videos mention and link to tres.js and cientos.js. 

We hope to share the 3D implementation solution based on Vue 3 and tres.js with more people in the Chinese community, as Vue 3 has a large user base in China. 

Our open-source repository is available at: https://github.com/hawk86104/icegl-three-vue-tres

image
image

If your team could help promote the link to our library, we would be immensely grateful. In the future, we will also contribute to tres.js and cientos.js, and we will bring a significant number of users from China as well.

Thank you once again.

**Comment by JaimeTorrealba** [comment]
@hawk86104 post on Twitter, tag us and we retweet it :)

**Comment by hawk86104** [comment]
> @hawk86104 post on Twitter, tag us and we retweet it :)

Thank you very much

**Pull request closed without merging**
