### PR TITLE
chore: update tres eslint

### PR DESCRIPTION
**Pull request by alvarosabu**
This applies the new flat linter to cientos

### CODE REVIEW

**Comment by JaimeTorrealba** [comment]
Is crashing the lock, remember how to solve that?

I know is easy but I don't remember right now jejeje

image

**Comment by alvarosabu** [comment]
@JaimeTorrealba I will take a look

**Review by JaimeTorrealba — APPROVED** [review]

**Comment by andretchen0** [comment]
I'm getting eslint errors after merging the latest `main` branch into `feat/fit`. 

```
pnpm run lint --fix
```

... leads to ...

```
cientos % pnpm run lint --fix

> @tresjs/cientos@3.8.0 lint /me/oss/cientos
> eslint . "--fix"


Oops! Something went wrong! :(

ESLint: 8.56.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tresjs/eslint-config' imported from /me/oss/cientos/eslint.config.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

As a consequence, can't push without the `--no-verify` flag and the linter CI step fails.

**Comment by andretchen0** [comment]
@alvarosabu

The new linter rules break valid Markdown. Please see: https://github.com/Tresjs/cientos/issues/398

**Pull request merged**
